title: Step N' Stones English Preschool
tagline: 保育の無償化の対象園になりました！
phone: "0853-27-9795"
address: |
  〒693-0001
  島根県出雲市今市町1189
instagram: https://www.instagram.com/sse_audax/
facebook: https://www.facebook.com/p/Step-N-Stones-100063709682049/
